[package]
name = "fo3_testbed"
version = "0.1.0"
edition = "2021"

[dependencies]
fo3_nif = { path = "../fo3_nif" }
fo3_gamebryo_core = { path = "../fo3_gamebryo_core" }
fo3_bsa = { path = "../fo3_bsa" }
fo3_vfs = { path = "../fo3_vfs" }
fo3_esm = { path = "../fo3_esm" }
fo3_render = { path = "../fo3_render" }
glam = { workspace = true }
